# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:10
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0002_auto_20170926_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='contact_info',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='full_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
