# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0003_auto_20170926_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='perkcategory',
            name='slug',
            field=models.SlugField(default='sport', verbose_name='SLUG'),
            preserve_default=False,
        ),
    ]
