# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import perks.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('perks', '0004_perkcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f')),
                ('code', models.CharField(default=perks.models.generate_code, max_length=4, verbose_name='\u041a\u043e\u0434 \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcations', to='members.Member')),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transacctions', to='perks.Perk')),
            ],
        ),
    ]
