# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import perks.models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0005_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '\u0422\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044f', 'verbose_name_plural': '\u0422\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default=perks.models.generate_code, editable=False, max_length=4, verbose_name='\u041a\u043e\u0434 \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='transcations', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='perk',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transacctions', to='perks.Perk'),
        ),
    ]
