# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0007_auto_20170927_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='members.Member', verbose_name='\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='perks.Perk', verbose_name='\u041f\u0440\u0438\u0432\u0438\u043b\u0435\u0433\u0438\u044f'),
        ),
    ]
