# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0008_auto_20170927_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perk',
            options={'verbose_name': '\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f', 'verbose_name_plural': '\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='perks.Perk', verbose_name='\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
