# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0009_auto_20170927_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='perkcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430 \u0434\u043b\u044f \u043c\u0435\u043d\u044e'),
        ),
    ]
