# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0010_perkcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perkcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/', verbose_name='SVG \u0438\u043a\u043e\u043d\u043a\u0430'),
        ),
    ]
