# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0011_auto_20171007_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='discount',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430'),
        ),
    ]
