# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0012_perk_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e?'),
        ),
    ]
