# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0013_perk_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perkimage',
            options={'verbose_name': '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430', 'verbose_name_plural': '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438'},
        ),
        migrations.RemoveField(
            model_name='perk',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='perk',
            name='is_active',
        ),
        migrations.AddField(
            model_name='perk',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='perk',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='perk',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='perk',
            name='main_image',
            field=models.ImageField(default='perks/pexel-photo.jpg', upload_to='perks/', verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perk',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='perk',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='\u0412\u0435\u0431-\u0441\u0430\u0439\u0442'),
        ),
    ]
