# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0014_auto_20171016_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
