# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0015_auto_20171016_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perk',
            name='email',
        ),
    ]
