# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 21:06
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0016_remove_perk_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='geoposition',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='\u0413\u0435\u043e\u043b\u043e\u043a\u0430\u0446\u0438\u044f'),
        ),
    ]
