# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0017_perk_geoposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perkimage',
            options={'verbose_name': '\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430', 'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438'},
        ),
        migrations.RemoveField(
            model_name='perk',
            name='main_image',
        ),
    ]
