# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/logos', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f'),
        ),
    ]
