# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20171015_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='enabled',
            field=models.BooleanField(default=True, editable=False, verbose_name='Включен'),
        ),
    ]
